CREATE  TABLE `dbtest`.`ACCOUNT` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `USERNAME` VARCHAR(256) NOT NULL ,
  `PASSWORD` VARCHAR(256) NOT NULL ,
  `TYPEID` CHAR(1) NULL ,
  `FIRSTNAME` VARCHAR(256) NULL ,
  `LASTNAME` VARCHAR(256) NULL ,
  `BIO` VARCHAR(256) NULL ,
  `AVATARPATH` VARCHAR(256) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;
